name: Build Android on debug mode
on:
  push:
    branches: [main]

  # Enable manual trigger
  workflow_dispatch:

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install libs
        run: yarn

      - name: Run tests
        run: yarn test

      - name: Build Android debug
        run: cd android && ./gradlew assembleRelease

      - name: Upload apk
        uses: actions/upload-artifact@v1
        with:
          name: android-debug
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Create release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: 'latest'
          prerelease: false
          title: 'Automatic Release-Candidate release'
          files: android/app/build/outputs/apk/release/app-release.apk
