name: Build Android on debug mode
on:
  push:
    branches: [main]

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install libs
        run: yarn

      - name: Run tests
        run: yarn test

      - name: Build Android debug
        run: cd android && ./gradlew assembleRelease

      - name: Upload apk
        uses: actions/upload-artifact@v1
        with:
          name: android-debug
          path: android/app/build/outputs/apk/release/app-release.apk
